name: Dependency Scan
on: [push, pull_request]

jobs:

  dependency-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install contrast-cli
        run: |
          npm install -g @contrast/contrast-cli 

      - name: Run
        run: |
          contrast-cli --api_key ${{ secrets.CONTRAST_API_KEY }} \
          --authorization ${{ secrets.CONTRAST_PERSONAL_SERVICE_KEY }} \
          --organization_id ${{ secrets.CONTRAST_ORGANIZATION_ID }} \
          --application_id ${{ secrets.CONTRAST_APPLICATION_ID }} \
          --host ce.contrastsecurity.com
